### ISSUE TITLE
Ad/item Display Page

### ISSUE THREAD

**Issue by lpgfx007** [dxitltd/Classifapp-Issue-Tracking#10]
Ad/item Display Page, Way the need to be.

All are marked in the photo !

![61561463-a6acda00-aa8c-11e9-81cd-9f86b86d4171](https://user-images.githubusercontent.com/1812171/62037124-d12b2f80-b210-11e9-8551-2764e0fb7b36.jpg)

**Comment by dxitltd** [comment]
We have the posted time here
![Simulator Screen Shot - iPhone 7 Plus - 2019-07-31 at 01 47 52](https://user-images.githubusercontent.com/52883432/62175414-8e16ac80-b335-11e9-9fbc-ad7b11e00403.png)
