### ISSUE TITLE
Search Page Results in the way the need to be

### ISSUE THREAD

**Issue by lpgfx007** [dxitltd/Classifapp-Issue-Tracking#18]
Search Page Results mark on the photo 

![data1](https://user-images.githubusercontent.com/1812171/62140032-e8007d80-b307-11e9-9507-aca2973d38fb.jpg)

**Comment by dxitltd** [comment]
The following changes are done.
1. The logo now should show on the search page
2. Search result count is now showing
3. Post time stamp added
4. Compay tag added, we are not showing the normal user tag as all other users are normal users by default.
5. Premium ads background color added. Color can be changed from the app control panel.
6. Highlighted ads background color added. Color can be changed from the app control panel.
7. Category and location added in Search

Premium ads icon has not been added. I will close this issue now, but you can create a new issue for the premium ad icon. Please note that if you have a design change suggestion please take a screenshot from our actual app and show the change suggestion there, this would be easier to understand and visualize how this would look on our app.
