### ISSUE TITLE
Ads Submit on app , Ads category expiation dates not  follow

### ISSUE THREAD

**Issue by lpgfx007** [dxitltd/Classifapp-Issue-Tracking#20]
Ads Submit on app, Ads category expiation dates not follow, its takes ( Never expires) 
On-site ads Submit its works category set Expiration date

![67933659_2426150307674796_1801610077682008064_n](https://user-images.githubusercontent.com/1812171/62482540-074d4e00-b7d3-11e9-8dab-a60e242348d9.jpg)

**Comment by lpgfx007** [comment]
https://scontent.fcmb2-1.fna.fbcdn.net/v/t1.15752-0/p480x480/67780565_2426150337674793_8481370458845872128_n.jpg?_nc_cat=105&_nc_eui2=AeFg23uevf8PUGMTTvBBCziGbOlstqjEmjVFAUSP7x1zbcPPtZKly-DuKYfvFEogQ4sCpl2UrzTc4WMXCvFv6D1onJai42jbwv-PbJKQleGfhg&_nc_oc=AQltKIw5HlJLMRgWNXDtHC1umRefwR7y5ilk4Uln1sFr280Iw5FyMCYdOT5_yvVO8OM&_nc_ht=scontent.fcmb2-1.fna&oh=ac47d0fbb82aa1244a8c91d8c0a75b48&oe=5DD1BF8E

**Comment by dxitltd** [comment]
This has been resolved.
