### ISSUE TITLE
Search / is the key to find users what they want. / app search update/

### ISSUE THREAD

**Issue by lpgfx007** [dxitltd/Classifapp-Issue-Tracking#9]
Search / is the key to find users what they want. / app search update/
All are marked in the photo!
![61561351-6188a800-aa8c-11e9-9d93-25a1c038eacf](https://user-images.githubusercontent.com/1812171/62037058-ae991680-b210-11e9-94e8-7c9bba273f07.jpg)

**Comment by dxitltd** [comment]
Until now we had two separate pages for search and filter. We have now merged these two pages into one where the search and filter can be done at the same time. So you can now search and specify the search location, category etc. 

![Simulator Screen Shot - iPhone 7 Plus - 2019-07-29 at 22 33 20](https://user-images.githubusercontent.com/52883432/62084291-e58f1c80-b250-11e9-806e-a67b35ebc0c6.png)

**Comment by lpgfx007** [comment]
Oki,

Search Page Results in the way the need to be, also Mark on the Photo
